controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

stripe_webhook:
    path: /stripe/webhook
    controller: App\Controller\StripeWebhookController::handle
    methods: [POST]

